version: "3"
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    environment:
      - tmp=tmp
    ports:
      - 11434:11434
    volumes: 
      - $PWD/ollama:/root/.ollama
    restart: unless-stopped
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports: 
      - 8080:8080 
    volumes: 
      - ./open-web-ui:/app/backend/data 
    environment: OLLAMA_BASE_URL=http://host.containers.internal:11434
